In [1]:
# 프로젝트 라이브러리
from thenews.__lib__ import *

# 나의 패키지
import __pymongo as mg
import __matplotlib as mpl

# 프로젝트 라이브러리
import News as news
import Layout as lay

# 모듈 라이브러리

# 오픈 패키지
%matplotlib inline

# 전역변수

# # # # # /Users/sambong/p/lib/LIB_PJT.py # # # # #

# # # # # /Users/sambong/p/lib/__debug.py # # # # #

# # # # # /Users/sambong/p/lib/__pymongo.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/Loader.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/Inserter.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/SaveDeduplicator.py # # # # #

# # # # # /Users/sambong/p/lib/__list.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/Backup.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/Updater.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/Report.py # # # # #

# # # # # /Users/sambong/p/lib/PyMongo/DB_Handler.py # # # # #

# # # # # /Users/sambong/p/news/NEWS_PJT.py # # # # #

# # # # # /Users/sambong/p/lib/__matplotlib.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/matplotlib_lib_LIBPJT.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/Line.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/matplotlib_lib.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/ViewFrame.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/Line_1Yaxis.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/Line_2Yaxes.py # # # # #

# # # # # /Users/sambong/p/lib/matplotlib/Histo.py # # # # #

# # # # # /Users/sambong/p/news/News.py # # # # #

# # # # # /Users/sambong/p/news/News_.py # # # # #

# # # # # /Users/sambong/p/news/News_Collector.py # # # # #

# # # # # /Users/sambong/p/lib/__datetime.py # # # # #

# # # # # /Users/sambong/p/lib/__requests.py # # # # #

# # # # # /Users/sambong/p/news/Layout.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Collector.py # # # # #

# # # # # /Users/sambong/p/news/Layout_ParserSaver.py # # # # #

# # # # # /Users/sambong/p/news/Layout_.py # # # # #

# # # # # /Users/sambong/p/news/Layout_URL.py # # # # #

# # # # # /Users/sambong/p/lib/__google.py # # # # #

# # # # # /Users/sambong/p/lib/Google/google_drive.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Parser.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Parser_Naver_mHome.py # # # # #

# # # # # /Users/sambong/p/news/Layout_ParserTargetHandler.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Parser_Naver_mNews_Home.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Report.py # # # # #

# # # # # /Users/sambong/p/news/Layout_Analyzer.py # # # # #

# # # # # /Users/sambong/p/news/News_Parser.py # # # # #

# # # # # /Users/sambong/p/lib/Programming_Collective_Intelligence.py # # # # #

# # # # # /Users/sambong/p/lib/Programming-Collective-Intelligence_building-smart-web-2.0-applications__Toby-Segaran__2007/newsfeatures.py # # # # #

# # # # # /Users/sambong/p/news/News_ParserTargetHandler.py # # # # #

# # # # # /Users/sambong/p/news/NaverWebParser.py # # # # #

# # # # # /Users/sambong/p/news/News_Report.py # # # # #

# # # # # /Users/sambong/p/news/LangAnalysis.py # # # # #

# # # # # /Users/sambong/p/news/LangAnalysis_.py # # # # #

# # # # # /Users/sambong/p/news/LangAnalysis_Collector.py # # # # #

# # # # # /Users/sambong/p/lib/__ETRI_AI.py # # # # #

# # # # # /Users/sambong/p/lib/ETRI_AI_OpenAPI/language_analysis_api.py # # # # #

# # # # # /Users/sambong/p/lib/ETRI_AI_OpenAPI/etri_ai_openAPI.py # # # # #

# # # # # /Users/sambong/p/lib/ETRI_AI_OpenAPI/lexicalRelation_analysis_api.py # # # # #

# # # # # /Users/sambong/p/lib/ETRI_AI_OpenAPI/etri_debuger.py # # # # #

# # # # # /Users/sambong/p/news/LangAnalysis_Parser.py # # # # #

# # # # # /Users/sambong/p/news/LangAnalysis_Loader.py # # # # #

# # # # # /Users/sambong/p/news/News_Cluster.py # # # # #

# # # # # /Users/sambong/p/news/News_Cluster_Algorithm.py # # # # #

# # # # # /Users/sambong/p/lib/__sklearn.py # # # # #

# # # # # /Users/sambong/p/news/News_ClusterReport.py # # # # #

# # # # # /Users/sambong/p/lib/__math_report.py # # # # #

In [2]:
news.report.화면배치TBL_href와_뉴스원본TBL_뉴스url간의_매핑관계_관찰(dbg_on=False, shown_cnt=1)

------------------------------------------------------------ TBL명:화면배치, URL컬럼명:href

============================================================find

============================================================distinct

============================================================distinct

============================================================distinct

------------------------------------------------------------ TBL명:뉴스_원본, URL컬럼명:뉴스_url

============================================================find

============================================================distinct

============================================================distinct

============================================================distinct

------------------------------------------------------------ TBL명:뉴스, URL컬럼명:뉴스_url

============================================================find

============================================================distinct

============================================================distinct

============================================================distinct
    TBL명  URL컬럼명  유일한_URL수  유일한_뉴스제목수  유일한_수집일시수  총_doc수
0   화면배치    href     15016       2328      10275  133215
1  뉴스_원본  뉴스_url     15016      15016       5016   19634
2     뉴스  뉴스_url     13545      11746      13789   18163

    TBL명  URL컬럼명  유일한_URL수  유일한_뉴스제목수  유일한_수집일시수  총_doc수
0   화면배치    href     15016       2328      10275  133215
1  뉴스_원본  뉴스_url     15016      15016       5016   19634
2     뉴스  뉴스_url     13545      11746      13789   18163

In [8]:
report.화면배치_원본TBL의_groupby_보고(gby_col명='r_status_code', dbg_on=False)

============================================================화면배치_원본TBL_jnorm로딩

    화면배치_원본TBL_파싱_v2
    status_code 로 df 상태에서 걸러내는 방법


============================================================find

               r_encoding  r_headers  r_text  r_url  _id  url  수집일시  파싱완료
r_status_code
200                   101        101     101    101  101  101   101   101

In [3]:
g

               r_encoding  r_headers  r_text  r_url  _id  url  수집일시  파싱완료
r_status_code
200                    95         95      95     95   95   95    95    95

In [6]:
report.화면배치_원본TBL_파싱완료체크(dbg_on=False)

============================================================화면배치_원본TBL_jnorm로딩

    화면배치_원본TBL_파싱_v2
    status_code 로 df 상태에서 걸러내는 방법


============================================================find

       r_encoding  r_headers  r_status_code  r_text  r_url  _id  url  수집일시
파싱완료
False          16         16             16      16     16   16   16    16
True           79         79             79      79     79   79   79    79

In [5]:
g

       r_encoding  r_headers  r_status_code  r_text  r_url  _id  url  수집일시
파싱완료
False          16         16             16      16     16   16   16    16
True           79         79             79      79     79   79   79    79